/**
 * Item Template Type Definitions
 *
 * Extends the EntityTemplate pattern for game-system-specific item types.
 * Inspired by Foundry VTT's item data model architecture with template mixins.
 *
 * @see docs/architecture/GAME_SYSTEMS.md
 */

import type {
  EntityTemplate,
  FieldDefinition,
  ComputedFieldDefinition,
  SectionDefinition,
  RollDefinition,
  ActionDefinition,
} from './game-systems.js';
import type { EffectChange, ChangeMode } from './activeEffect.js';

// ============================================================================
// ITEM CATEGORIES
// ============================================================================

/**
 * Standard item categories supported across game systems.
 * Each game system can define which categories it uses.
 */
export type ItemCategory =
  | 'weapon'      // Weapons and attack items
  | 'armor'       // Armor, shields, and protective gear
  | 'spell'       // Spells and magical abilities
  | 'consumable'  // Potions, scrolls, ammunition
  | 'feature'     // Class features, feats, racial traits
  | 'tool'        // Artisan tools, gaming sets, instruments
  | 'loot'        // Treasure, trade goods, gems
  | 'container'   // Bags, backpacks, storage items
  | 'class'       // Character class (for progression)
  | 'race'        // Character race/ancestry
  | 'background'  // Character background
  | 'custom';     // User-defined category

/**
 * Item rarity levels (D&D-style, but applicable to many systems)
 */
export type ItemRarity =
  | 'common'
  | 'uncommon'
  | 'rare'
  | 'very_rare'
  | 'legendary'
  | 'artifact';

/**
 * Attunement states for magic items
 */
export type AttunementState =
  | 'none'        // No attunement required
  | 'required'    // Requires attunement but not yet attuned
  | 'attuned';    // Currently attuned

// ============================================================================
// ITEM TEMPLATE
// ============================================================================

/**
 * ItemTemplate extends EntityTemplate with item-specific properties.
 * Templates define the schema, behavior, and effects of a type of item.
 */
export interface ItemTemplate extends Omit<EntityTemplate, 'entityType'> {
  entityType: 'item';

  /**
   * Item category for filtering, organization, and UI rendering
   */
  category: ItemCategory;

  /**
   * Parent template ID for inheritance.
   * Child templates inherit fields, effects, and behaviors from parent.
   * Example: "martial_weapon" extends "weapon"
   */
  extends?: string;

  /**
   * Configuration for physical/tangible items
   */
  physical?: PhysicalItemConfig;

  /**
   * Configuration for items that can be equipped/worn
   */
  equippable?: EquippableItemConfig;

  /**
   * Configuration for items that can be activated/used
   */
  activation?: ActivationConfig;

  /**
   * Resource consumption when item is used
   */
  consumes?: ConsumptionConfig;

  /**
   * Active effects generated by this item when equipped/attuned/activated
   */
  effects?: ItemEffectDefinition[];

  /**
   * Container-specific configuration (for bags, backpacks, etc.)
   */
  container?: ContainerConfig;
}

// ============================================================================
// PHYSICAL ITEM CONFIGURATION
// ============================================================================

/**
 * Configuration for physical/tangible items with weight, price, etc.
 */
export interface PhysicalItemConfig {
  /**
   * Whether this item type has weight
   */
  hasWeight: boolean;

  /**
   * Whether this item type has a price
   */
  hasPrice: boolean;

  /**
   * Whether this item type tracks quantity
   */
  hasQuantity: boolean;

  /**
   * Whether multiple items can be stacked (quantity > 1)
   */
  stackable: boolean;

  /**
   * Default weight unit for display
   */
  weightUnit?: string; // 'lb', 'kg', etc.

  /**
   * Default currency unit for price
   */
  priceUnit?: string; // 'gp', 'cp', 'credits', etc.
}

// ============================================================================
// EQUIPPABLE ITEM CONFIGURATION
// ============================================================================

/**
 * Equipment slot where an item can be worn/held
 */
export type EquipmentSlot =
  | 'mainHand'    // Primary weapon hand
  | 'offHand'     // Secondary/shield hand
  | 'twoHand'     // Two-handed weapon
  | 'armor'       // Body armor
  | 'head'        // Helmet, circlet
  | 'cloak'       // Cape, cloak
  | 'neck'        // Amulet, necklace
  | 'ring'        // Rings (usually have multiple slots)
  | 'belt'        // Belt, girdle
  | 'hands'       // Gloves, gauntlets
  | 'feet'        // Boots, shoes
  | 'none';       // Not equippable

/**
 * Configuration for items that can be equipped/worn
 */
export interface EquippableItemConfig {
  /**
   * Equipment slot(s) where this item can be worn.
   * Some items can fit multiple slots (e.g., versatile weapons)
   */
  equipSlots: EquipmentSlot[];

  /**
   * Whether this item requires attunement to gain magical benefits
   */
  requiresAttunement: boolean;

  /**
   * Text description of attunement requirements (e.g., "requires attunement by a spellcaster")
   */
  attunementRequirements?: string;

  /**
   * Maximum number of this item type that can be equipped
   */
  maxEquipped?: number;
}

// ============================================================================
// ACTIVATION CONFIGURATION
// ============================================================================

/**
 * Action type required to activate/use an item
 */
export type ActivationType =
  | 'action'        // Standard action
  | 'bonus_action'  // Bonus action
  | 'reaction'      // Reaction
  | 'free'          // Free action
  | 'minute'        // Takes 1+ minutes
  | 'hour'          // Takes 1+ hours
  | 'special'       // Special timing
  | 'none';         // Passive, no action required

/**
 * Configuration for item activation/usage
 */
export interface ActivationConfig {
  /**
   * Type of action required to use this item
   */
  type: ActivationType;

  /**
   * Number of actions required (for systems with action points)
   */
  cost?: number;

  /**
   * Condition or trigger for activation
   */
  condition?: string;

  /**
   * Verbal component or incantation required
   */
  verbal?: boolean;

  /**
   * Somatic/gesture component required
   */
  somatic?: boolean;
}

// ============================================================================
// CONSUMPTION CONFIGURATION
// ============================================================================

/**
 * Type of resource consumed when item is used
 */
export type ConsumptionType =
  | 'charges'      // Item has limited charges
  | 'quantity'     // Consumes from quantity (ammunition, potions)
  | 'spell_slot'   // Consumes spell slot
  | 'resource'     // Consumes actor resource (hit dice, etc.)
  | 'item'         // Consumes another item
  | 'none';        // No consumption

/**
 * Configuration for resource consumption when item is used
 */
export interface ConsumptionConfig {
  /**
   * Type of resource consumed
   */
  type: ConsumptionType;

  /**
   * Target resource ID or 'self' for item's own charges/quantity
   */
  target?: string;

  /**
   * Amount consumed per use (can be formula like "@item.level")
   */
  amount: number | string;

  /**
   * What happens when charges/quantity reach 0
   */
  onEmpty?: 'destroy' | 'disable' | 'nothing';

  /**
   * How charges are recovered
   */
  recovery?: RecoveryConfig;
}

/**
 * Configuration for charge/use recovery
 */
export interface RecoveryConfig {
  /**
   * When recovery occurs
   */
  trigger: 'short_rest' | 'long_rest' | 'dawn' | 'dusk' | 'turn_start' | 'manual';

  /**
   * Amount recovered (number or dice formula like "1d6+1")
   */
  amount: number | string;

  /**
   * Whether recovery is automatic or requires a roll
   */
  automatic?: boolean;
}

// ============================================================================
// ITEM EFFECTS
// ============================================================================

/**
 * Trigger condition for when an item effect becomes active
 */
export type EffectTrigger =
  | 'passive'     // Always active
  | 'equipped'    // Active when equipped
  | 'attuned'     // Active when attuned
  | 'activated'   // Active when item is used
  | 'held';       // Active when held (not necessarily equipped)

// EffectChange and ChangeMode are imported from './activeEffect.js'
// to avoid duplication and ensure consistency across the system

/**
 * Duration configuration for temporary effects
 */
export interface EffectDuration {
  /**
   * Duration value (number or formula)
   */
  value: number | string;

  /**
   * Duration units
   */
  units: 'round' | 'turn' | 'minute' | 'hour' | 'day' | 'permanent' | 'special';

  /**
   * Whether effect requires concentration (for spells)
   */
  concentration?: boolean;
}

/**
 * Defines an active effect generated by an item
 */
export interface ItemEffectDefinition {
  /**
   * Unique identifier within the item template
   */
  id: string;

  /**
   * Display name of the effect
   */
  name: string;

  /**
   * Icon for the effect (path to image)
   */
  icon?: string;

  /**
   * Description of what the effect does
   */
  description?: string;

  /**
   * When this effect becomes active
   */
  trigger: EffectTrigger;

  /**
   * Property changes applied by this effect
   */
  changes: EffectChange[];

  /**
   * Whether effect transfers to actor when item is equipped
   */
  transfer: boolean;

  /**
   * Duration for temporary effects
   */
  duration?: EffectDuration;

  /**
   * Effect type category
   */
  effectType?: 'buff' | 'debuff' | 'condition' | 'passive' | 'aura';

  /**
   * Whether effect is hidden from players
   */
  hidden?: boolean;
}

// ============================================================================
// CONTAINER CONFIGURATION
// ============================================================================

/**
 * Configuration for container items (bags, backpacks, chests)
 */
export interface ContainerConfig {
  /**
   * Maximum weight capacity (0 = unlimited)
   */
  weightCapacity: number;

  /**
   * Maximum number of items (0 = unlimited)
   */
  itemCapacity: number;

  /**
   * Weight reduction for items inside (1 = full weight, 0.5 = half, 0 = weightless)
   */
  weightMultiplier: number;

  /**
   * Whether container can hold other containers
   */
  allowNesting: boolean;

  /**
   * Item types that can be placed in this container
   */
  allowedCategories?: ItemCategory[];
}

// ============================================================================
// CUSTOM TEMPLATE (Database-stored)
// ============================================================================

/**
 * A custom item template created by a GM and stored in the database.
 * Extends the base ItemTemplate with persistence metadata.
 */
export interface CustomItemTemplate extends ItemTemplate {
  /**
   * Database ID for the custom template
   */
  dbId: string;

  /**
   * Campaign this template belongs to
   */
  campaignId: string;

  /**
   * User who created the template
   */
  createdBy: string;

  /**
   * Whether template is shared with other GMs in campaign
   */
  shared: boolean;

  /**
   * Creation timestamp
   */
  createdAt: Date;

  /**
   * Last update timestamp
   */
  updatedAt: Date;
}

// ============================================================================
// TEMPLATE REQUESTS
// ============================================================================

/**
 * Request to create a custom item template
 */
export interface CreateItemTemplateRequest {
  systemId: string;
  name: string;
  category: ItemCategory;
  extends?: string;
  fields?: FieldDefinition[];
  computedFields?: ComputedFieldDefinition[];
  sections?: SectionDefinition[];
  rolls?: RollDefinition[];
  actions?: ActionDefinition[];
  physical?: PhysicalItemConfig;
  equippable?: EquippableItemConfig;
  activation?: ActivationConfig;
  consumes?: ConsumptionConfig;
  effects?: ItemEffectDefinition[];
  container?: ContainerConfig;
  shared?: boolean;
}

/**
 * Request to update a custom item template
 */
export interface UpdateItemTemplateRequest {
  name?: string;
  category?: ItemCategory;
  extends?: string;
  fields?: FieldDefinition[];
  computedFields?: ComputedFieldDefinition[];
  sections?: SectionDefinition[];
  rolls?: RollDefinition[];
  actions?: ActionDefinition[];
  physical?: PhysicalItemConfig;
  equippable?: EquippableItemConfig;
  activation?: ActivationConfig;
  consumes?: ConsumptionConfig;
  effects?: ItemEffectDefinition[];
  container?: ContainerConfig;
  shared?: boolean;
}

// ============================================================================
// VALIDATION
// ============================================================================

/**
 * Result of validating item data against a template
 */
export interface ItemValidationResult {
  valid: boolean;
  errors: ItemValidationError[];
  warnings: ItemValidationWarning[];
}

/**
 * A validation error that prevents item creation/update
 */
export interface ItemValidationError {
  field: string;
  message: string;
  code: string;
}

/**
 * A validation warning that doesn't prevent creation but should be noted
 */
export interface ItemValidationWarning {
  field: string;
  message: string;
  code: string;
}
